name: fruits_dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.6.1
  dartz: ^0.10.1
  firebase_core: ^3.10.0
  firebase_storage: ^12.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.16
  gap: ^3.0.1
  get_it: ^8.0.3
  image_picker: ^1.1.2
  modal_progress_hud_nsn: ^0.5.1
  path: ^1.9.0
  skeletonizer: ^1.4.2
  supabase_flutter: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
