// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ5DIYKGzjpi2urVLCF8DO36IfulTnN_U',
    appId: '1:410255361500:web:8c0debbbd21a6e54e67b19',
    messagingSenderId: '410255361500',
    projectId: 'fruits-123',
    authDomain: 'fruits-123.firebaseapp.com',
    storageBucket: 'fruits-123.firebasestorage.app',
    measurementId: 'G-SG3SP8M79R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARKcIowCFXZTLGGD7wkimeiLbHS18Ceyc',
    appId: '1:410255361500:android:0db280eaa27d1ffde67b19',
    messagingSenderId: '410255361500',
    projectId: 'fruits-123',
    storageBucket: 'fruits-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqKuJyguYquMb10nEvm11ZEowcQYlCETM',
    appId: '1:410255361500:ios:97ebf8dc38064427e67b19',
    messagingSenderId: '410255361500',
    projectId: 'fruits-123',
    storageBucket: 'fruits-123.firebasestorage.app',
    iosClientId: '410255361500-vgu23i92qga5686akb6qt99e2oa9vfur.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqKuJyguYquMb10nEvm11ZEowcQYlCETM',
    appId: '1:410255361500:ios:97ebf8dc38064427e67b19',
    messagingSenderId: '410255361500',
    projectId: 'fruits-123',
    storageBucket: 'fruits-123.firebasestorage.app',
    iosClientId: '410255361500-vgu23i92qga5686akb6qt99e2oa9vfur.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK4-GwsWm_NnJpeCDLbaLV9siQ0XFaOT4',
    appId: '1:410255361500:web:77d087db0bcae457e67b19',
    messagingSenderId: '410255361500',
    projectId: 'fruits-123',
    authDomain: 'fruits-123.firebaseapp.com',
    storageBucket: 'fruits-123.firebasestorage.app',
    measurementId: 'G-MLW84J1LSP',
  );
}
